-- QA simulation seed data removed.
-- This migration inserted fake leads, appointments, calls, funnel events,
-- trigger logs, offer impressions, and audit logs using hard-coded setter/closer
-- user IDs that do not exist in a fresh dev database.