
INSERT INTO public.ab_slot_weights (slot, variant, weight) VALUES
('mos_lp_action_mode','A_90s_potenzialcheck',0.2),
('mos_lp_action_mode','B_5_fragen_potenzialcheck',0.2),
('mos_lp_action_mode','C_potenzial_kostenlos_pruefen',0.2),
('mos_lp_action_mode','D_closing_passt_zu_dir',0.2),
('mos_lp_action_mode','E_erfolgreich_als_closer',0.2),
('mos_lp_visual_focus','A_cta_only',0.25),
('mos_lp_visual_focus','B_cta_progress',0.25),
('mos_lp_visual_focus','C_cta_quizpreview',0.25),
('mos_lp_visual_focus','D_cta_resultpreview',0.25),
('mos_lp_zero_text','A_normal_text',0.25),
('mos_lp_zero_text','B_half_text',0.25),
('mos_lp_zero_text','C_minimal_three_lines',0.25),
('mos_lp_zero_text','D_cta_centric',0.25),
('mos_lp_instant_start','A_normal',0.25),
('mos_lp_instant_start','B_quiz_visible',0.25),
('mos_lp_instant_start','C_scroll_to_q1',0.25),
('mos_lp_instant_start','D_cta_opens_q1',0.25),
('mos_lp_message_match','karriere',0.16),
('mos_lp_message_match','freiheit',0.16),
('mos_lp_message_match','remote',0.16),
('mos_lp_message_match','high_ticket',0.16),
('mos_lp_message_match','weiterentwicklung',0.16),
('mos_lp_message_match','einkommen',0.20),
('mos_q1_momentum','A_normal',0.2),
('mos_q1_momentum','B_1_of_5',0.2),
('mos_q1_momentum','C_progress_bar',0.2),
('mos_q1_momentum','D_90_seconds',0.2),
('mos_q1_momentum','E_no_application',0.2)
ON CONFLICT (slot, variant) DO NOTHING;
